//*********************************************************
//  Autogenerated 29.10.2011 16:49:28
//*********************************************************
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/*
!re
=.id=*1000009
=name=Vin_Weiss
=parent==1M_AA
=packet-mark=V_Weiss
=limit-at=80000
=queue=default
=priority=7
=max-limit=2000000
=burst-limit=0
=burst-threshold=0
=burst-time=00:00:00
=invalid=false
=disabled=false
*/
namespace Tik4Net.Objects.Queue
{
    /// <summary>
    /// Represents one row in /queue/tree on mikrotik router.
    /// </summary>
    [TikEntity("/queue/tree", TikEntityEditMode.Editable, Tik4Net.Connector.ExecuteReaderBehaviors.None)]    
    public sealed partial class QueueTree: TikEntityBase , ITikEntityWithId
    {
        /// <summary>
        /// Row .id property.
        /// </summary>
        [TikProperty(".id", typeof(string), true, TikPropertyEditMode.ReadOnly)]
        public string Id 
        { 
            get { return Properties.GetAsStringOrNull(".id"); }
            // Property R/O set { Properties.SetPropertyValue(".id", value); }
        }

        /// <summary>
        /// Row burst-limit property.
        /// </summary>
        [TikProperty("burst-limit", typeof(long?), false, TikPropertyEditMode.Editable)]
        public long? BurstLimit 
        { 
            get { return Properties.GetAsInt64OrNull("burst-limit"); }
            set { Properties.SetPropertyValue("burst-limit", value); }
        }        	

        /// <summary>
        /// Row burst-threshold property.
        /// </summary>
        [TikProperty("burst-threshold", typeof(long?), false, TikPropertyEditMode.Editable)]
        public long? BurstThreshold 
        { 
            get { return Properties.GetAsInt64OrNull("burst-threshold"); }
            set { Properties.SetPropertyValue("burst-threshold", value); }
        }        	

        /// <summary>
        /// Row burst-time property.
        /// </summary>
        [TikProperty("burst-time", typeof(string), false, TikPropertyEditMode.Editable)]
        public string BurstTime 
        { 
            get { return Properties.GetAsStringOrNull("burst-time"); }
            set { Properties.SetPropertyValue("burst-time", value); }
        }        	

        /// <summary>
        /// Row disabled property.
        /// </summary>
        [TikProperty("disabled", typeof(bool), true, TikPropertyEditMode.Editable)]
        public bool Disabled 
        { 
            get { return Properties.GetAsBoolean("disabled"); }
            set { Properties.SetPropertyValue("disabled", value); }
        }        	

        /// <summary>
        /// Row disabled property variant that could be used for bindings (doesn't throw exceptions when not set - underlying property is madatory).
        /// Use <see cref="Disabled"/> in other cases.
        /// </summary>
        public bool? DisabledOrNull 
        { 
            get { return Properties.GetAsBooleanOrNull("disabled"); }
            set { Properties.SetPropertyValue("disabled", value); }
        }   
                
        /// <summary>
        /// Gets a value indicating whether <see cref="Disabled"/> property has been set.
        /// </summary>
        /// <value><c>true</c> if <see cref="Disabled"/> has been set; otherwise, <c>false</c>.</value>        
        public bool DisabledIsSet
        {
            get { return Properties.ContainsAssignedProperty("disabled"); }
        }        

        /// <summary>
        /// Row invalid property.
        /// </summary>
        [TikProperty("invalid", typeof(bool?), false, TikPropertyEditMode.Editable)]
        public bool? Invalid 
        { 
            get { return Properties.GetAsBooleanOrNull("invalid"); }
            set { Properties.SetPropertyValue("invalid", value); }
        }        	

        /// <summary>
        /// Row limit-at property.
        /// </summary>
        [TikProperty("limit-at", typeof(long?), false, TikPropertyEditMode.Editable)]
        public long? LimitAt 
        { 
            get { return Properties.GetAsInt64OrNull("limit-at"); }
            set { Properties.SetPropertyValue("limit-at", value); }
        }        	

        /// <summary>
        /// Row max-limit property.
        /// </summary>
        [TikProperty("max-limit", typeof(long?), false, TikPropertyEditMode.Editable)]
        public long? MaxLimit 
        { 
            get { return Properties.GetAsInt64OrNull("max-limit"); }
            set { Properties.SetPropertyValue("max-limit", value); }
        }        	

        /// <summary>
        /// Row name property.
        /// </summary>
        [TikProperty("name", typeof(string), true, TikPropertyEditMode.Editable)]
        public string Name 
        { 
            get { return Properties.GetAsString("name"); }
            set { Properties.SetPropertyValue("name", value); }
        }        	

        /// <summary>
        /// Row name property variant that could be used for bindings (doesn't throw exceptions when not set - underlying property is madatory).
        /// Use <see cref="Name"/> in other cases.
        /// </summary>
        public string NameOrNull 
        { 
            get { return Properties.GetAsStringOrNull("name"); }
            set { Properties.SetPropertyValue("name", value); }
        }   
                
        /// <summary>
        /// Gets a value indicating whether <see cref="Name"/> property has been set.
        /// </summary>
        /// <value><c>true</c> if <see cref="Name"/> has been set; otherwise, <c>false</c>.</value>        
        public bool NameIsSet
        {
            get { return Properties.ContainsAssignedProperty("name"); }
        }        

        /// <summary>
        /// Row packet-mark property.
        /// </summary>
        [TikProperty("packet-mark", typeof(string), false, TikPropertyEditMode.Editable)]
        public string PacketMark 
        { 
            get { return Properties.GetAsStringOrNull("packet-mark"); }
            set { Properties.SetPropertyValue("packet-mark", value); }
        }        	

        /// <summary>
        /// Row parent property.
        /// </summary>
        [TikProperty("parent", typeof(string), false, TikPropertyEditMode.Editable)]
        public string Parent 
        { 
            get { return Properties.GetAsStringOrNull("parent"); }
            set { Properties.SetPropertyValue("parent", value); }
        }        	

        /// <summary>
        /// Row priority property.
        /// </summary>
        [TikProperty("priority", typeof(long?), false, TikPropertyEditMode.Editable)]
        public long? Priority 
        { 
            get { return Properties.GetAsInt64OrNull("priority"); }
            set { Properties.SetPropertyValue("priority", value); }
        }        	

        /// <summary>
        /// Row queue property.
        /// </summary>
        [TikProperty("queue", typeof(string), false, TikPropertyEditMode.Editable)]
        public string Queue 
        { 
            get { return Properties.GetAsStringOrNull("queue"); }
            set { Properties.SetPropertyValue("queue", value); }
        }        	
    }
    
    /// <summary>
    /// Represents list of rows in /queue/tree on mikrotik router.
    /// </summary>    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix")]    
    public sealed partial class QueueTreeList : TikUnorderedList<QueueTree> , IEditableTikList
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="QueueTreeList"/> class.
        /// Default active session (<see cref="TikSession.ActiveSession"/> is used).
        /// </summary>
        public QueueTreeList() 
            : base()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="QueueTreeList"/> class.
        /// </summary>
        /// <param name="session">The session used to access mikrotik.</param>
        public QueueTreeList(TikSession session)
            : base(session)
        {
        }

		        /// <summary>
        /// Saves this instance - saves all entities that are in <see cref="TikEntityBase.IsModified"/>, 
        /// <see cref="TikEntityBase.IsMarkedDeleted"/> and <see cref="TikEntityBase.IsMarkedNew"/> states.
        /// Uses session from constructor.
        /// </summary>        
        public void Save()
        {
			SaveInternal();
		}        

	}           
}