//*********************************************************
//  Autogenerated 9.4.2011 12:11:10
//*********************************************************
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/*
!re
=.id=*1000009
=name=Vin_Weiss
=parent==1M_AA
=packet-mark=V_Weiss
=limit-at=80000
=queue=default
=priority=7
=max-limit=2000000
=burst-limit=0
=burst-threshold=0
=burst-time=00:00:00
=invalid=false
=disabled=false
*/
namespace Tik4Net.Objects.Queue
{
    /// <summary>
    /// Represents one row in /queue/tree on mikrotik router.
    /// </summary>
    [TikEntity("/queue/tree", TikEntityEditMode.Editable)]    
    public sealed partial class QueueTree: TikEntityBase
    {
        /// <summary>
        /// Row burst-limit property.
        /// </summary>
        [TikProperty("burst-limit", typeof(long?), false, TikPropertyEditMode.Editable)]
        public long? BurstLimit 
        { 
            get { return Properties.GetAsInt64OrNull("burst-limit"); }
            set { Properties.SetAttribute("burst-limit", value); }
        }

        /// <summary>
        /// Row burst-threshold property.
        /// </summary>
        [TikProperty("burst-threshold", typeof(long?), false, TikPropertyEditMode.Editable)]
        public long? BurstThreshold 
        { 
            get { return Properties.GetAsInt64OrNull("burst-threshold"); }
            set { Properties.SetAttribute("burst-threshold", value); }
        }        	

        /// <summary>
        /// Row burst-time property.
        /// </summary>
        [TikProperty("burst-time", typeof(string), false, TikPropertyEditMode.Editable)]
        public string BurstTime 
        { 
            get { return Properties.GetAsStringOrNull("burst-time"); }
            set { Properties.SetAttribute("burst-time", value); }
        }        	

        /// <summary>
        /// Row disabled property.
        /// </summary>
        [TikProperty("disabled", typeof(bool), true, TikPropertyEditMode.Editable)]
        public bool Disabled 
        { 
            get { return Properties.GetAsBoolean("disabled"); }
            set { Properties.SetAttribute("disabled", value); }
        }        	

        /// <summary>
        /// Row invalid property.
        /// </summary>
        [TikProperty("invalid", typeof(bool?), false, TikPropertyEditMode.Editable)]
        public bool? Invalid 
        { 
            get { return Properties.GetAsBooleanOrNull("invalid"); }
            set { Properties.SetAttribute("invalid", value); }
        }        	

        /// <summary>
        /// Row limit-at property.
        /// </summary>
        [TikProperty("limit-at", typeof(long?), false, TikPropertyEditMode.Editable)]
        public long? LimitAt 
        { 
            get { return Properties.GetAsInt64OrNull("limit-at"); }
            set { Properties.SetAttribute("limit-at", value); }
        }        	

        /// <summary>
        /// Row max-limit property.
        /// </summary>
        [TikProperty("max-limit", typeof(long?), false, TikPropertyEditMode.Editable)]
        public long? MaxLimit 
        { 
            get { return Properties.GetAsInt64OrNull("max-limit"); }
            set { Properties.SetAttribute("max-limit", value); }
        }        	

        /// <summary>
        /// Row name property.
        /// </summary>
        [TikProperty("name", typeof(string), true, TikPropertyEditMode.Editable)]
        public string Name 
        { 
            get { return Properties.GetAsString("name"); }
            set { Properties.SetAttribute("name", value); }
        }        	

        /// <summary>
        /// Row packet-mark property.
        /// </summary>
        [TikProperty("packet-mark", typeof(string), false, TikPropertyEditMode.Editable)]
        public string PacketMark 
        { 
            get { return Properties.GetAsStringOrNull("packet-mark"); }
            set { Properties.SetAttribute("packet-mark", value); }
        }        	

        /// <summary>
        /// Row parent property.
        /// </summary>
        [TikProperty("parent", typeof(string), false, TikPropertyEditMode.Editable)]
        public string Parent 
        { 
            get { return Properties.GetAsStringOrNull("parent"); }
            set { Properties.SetAttribute("parent", value); }
        }        	

        /// <summary>
        /// Row priority property.
        /// </summary>
        [TikProperty("priority", typeof(long?), false, TikPropertyEditMode.Editable)]
        public long? Priority 
        { 
            get { return Properties.GetAsInt64OrNull("priority"); }
            set { Properties.SetAttribute("priority", value); }
        }        	

        /// <summary>
        /// Row queue property.
        /// </summary>
        [TikProperty("queue", typeof(string), false, TikPropertyEditMode.Editable)]
        public string Queue 
        { 
            get { return Properties.GetAsStringOrNull("queue"); }
            set { Properties.SetAttribute("queue", value); }
        }        	
    }
    
    /// <summary>
    /// Represents list of rows in /queue/tree on mikrotik router.
    /// </summary>    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix")]    
    public sealed partial class QueueTreeList : TikUnorderedList<QueueTree>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="QueueTreeList"/> class.
        /// Default active session (<see cref="TikSession.ActiveSession"/> is used).
        /// </summary>
        public QueueTreeList() 
            : base()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="QueueTreeList"/> class.
        /// </summary>
        /// <param name="session">The session used to access mikrotik.</param>
        public QueueTreeList(TikSession session)
            : base(session)
        {
        }
    }           
}