// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project. 
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc. 
//
// To add a suppression to this file, right-click the message in the 
// Error List, point to "Suppress Message(s)", and click 
// "In Project Suppression File". 
// You do not need to add suppressions to this file manually. 

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "Tik4Net")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "Tik4Net.Session")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "Tik4Net.Session.Api")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "net")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "tik")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "Tik4Net.Ip.Firewall")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "Tik4Net.Queue")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "SrcAddress", Scope = "member", Target = "Tik4Net.Ip.Firewall.FirewallMangle.#SrcAddress")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Src", Scope = "member", Target = "Tik4Net.Ip.Firewall.FirewallMangle.#SrcAddress")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "SrcAddress", Scope = "member", Target = "Tik4Net.Ip.Firewall.FirewallMangle.#SrcAddressList")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Src", Scope = "member", Target = "Tik4Net.Ip.Firewall.FirewallMangle.#SrcAddressList")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "PcqQueues", Scope = "member", Target = "Tik4Net.Queue.QueueTree.#PcqQueues")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Pcq", Scope = "member", Target = "Tik4Net.Queue.QueueTree.#PcqQueues")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Hdd", Scope = "member", Target = "Tik4Net.Objects.System.SystemResource.#FreeHddSpace")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Hdd", Scope = "member", Target = "Tik4Net.Objects.System.SystemResource.#TotalHddSpace")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId = "session", Scope = "member", Target = "Tik4Net.TikListBase`1.#LoadItemsInternal(System.Collections.Generic.Dictionary`2<System.String,System.String>,Tik4Net.TikSession)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1726:UsePreferredTerms", MessageId = "Flags", Scope = "member", Target = "Tik4Net.Objects.Ip.Firewall.FirewallMangle.#TcpFlags")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "Tik4Net.Connector")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "Tik4Net.Objects")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "Tik4Net.Objects.System")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "Tik4Net.Objects.Queue")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "Tik4Net.Objects.Ip.Firewall")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Ssh", Scope = "member", Target = "Tik4Net.TikConnectorType.#Ssh")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "SrcAddress", Scope = "member", Target = "Tik4Net.Objects.Ip.Firewall.FirewallMangle.#SrcAddress")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Src", Scope = "member", Target = "Tik4Net.Objects.Ip.Firewall.FirewallMangle.#SrcAddress")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "SrcAddress", Scope = "member", Target = "Tik4Net.Objects.Ip.Firewall.FirewallMangle.#SrcAddressList")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Src", Scope = "member", Target = "Tik4Net.Objects.Ip.Firewall.FirewallMangle.#SrcAddressList")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "Tik4Net.Connector.Api")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "SrcAddress", Scope = "member", Target = "Tik4Net.Objects.Ip.Firewall.FirewallFilter.#SrcAddress")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Src", Scope = "member", Target = "Tik4Net.Objects.Ip.Firewall.FirewallFilter.#SrcAddress")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "SrcAddress", Scope = "member", Target = "Tik4Net.Objects.Ip.Firewall.FirewallFilter.#SrcAddressList")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Src", Scope = "member", Target = "Tik4Net.Objects.Ip.Firewall.FirewallFilter.#SrcAddressList")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Src", Scope = "member", Target = "Tik4Net.Objects.Ip.Firewall.FirewallFilter.#SrcPort")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "SrcAddress", Scope = "member", Target = "Tik4Net.Objects.Ip.Firewall.FirewallNat.#SrcAddress")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Src", Scope = "member", Target = "Tik4Net.Objects.Ip.Firewall.FirewallNat.#SrcAddress")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "SrcAddress", Scope = "member", Target = "Tik4Net.Objects.Ip.Firewall.FirewallNat.#SrcAddressList")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Src", Scope = "member", Target = "Tik4Net.Objects.Ip.Firewall.FirewallNat.#SrcAddressList")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "SrcAddress", Scope = "member", Target = "Tik4Net.Objects.Ip.Firewall.FirewallNat.#SrcAddressType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Src", Scope = "member", Target = "Tik4Net.Objects.Ip.Firewall.FirewallNat.#SrcAddressType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Pfifo", Scope = "member", Target = "Tik4Net.Objects.Queue.QueueType.#PfifoLimit")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Avg", Scope = "member", Target = "Tik4Net.Objects.Queue.QueueType.#RedAvgPacket")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Sfq", Scope = "member", Target = "Tik4Net.Objects.Queue.QueueType.#SfqAllot")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Sfq", Scope = "member", Target = "Tik4Net.Objects.Queue.QueueType.#SfqPerturb")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "Tik4Net.Objects.Interfaces")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716:IdentifiersShouldNotMatchKeywords", MessageId = "Interface", Scope = "type", Target = "Tik4Net.Objects.Interface")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "mtu", Scope = "member", Target = "Tik4Net.Objects.Interface.#L2mtu")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "mtu", Scope = "member", Target = "Tik4Net.Objects.Interface.#L2mtu")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Mtu", Scope = "member", Target = "Tik4Net.Objects.Interface.#Mtu")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1721:PropertyNamesShouldNotMatchGetMethods", Scope = "member", Target = "Tik4Net.Objects.Interface.#Type")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "mtu", Scope = "member", Target = "Tik4Net.Objects.Interfaces.InterfaceEthernet.#L2mtu")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "mtu", Scope = "member", Target = "Tik4Net.Objects.Interfaces.InterfaceEthernet.#L2mtu")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Mtu", Scope = "member", Target = "Tik4Net.Objects.Interfaces.InterfaceEthernet.#Mtu")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "Ap", Scope = "member", Target = "Tik4Net.Objects.Interfaces.InterfaceWireless.#DefaultApTxLimit")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "Tx", Scope = "member", Target = "Tik4Net.Objects.Interfaces.InterfaceWireless.#DefaultApTxLimit")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "Tx", Scope = "member", Target = "Tik4Net.Objects.Interfaces.InterfaceWireless.#DefaultClientTxLimit")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Ssid", Scope = "member", Target = "Tik4Net.Objects.Interfaces.InterfaceWireless.#HideSsid")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "mtu", Scope = "member", Target = "Tik4Net.Objects.Interfaces.InterfaceWireless.#L2mtu")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Mtu", Scope = "member", Target = "Tik4Net.Objects.Interfaces.InterfaceWireless.#Mtu")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "mtu", Scope = "member", Target = "Tik4Net.Objects.Interfaces.InterfaceWireless.#L2mtu")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Ssid", Scope = "member", Target = "Tik4Net.Objects.Interfaces.InterfaceWireless.#Ssid")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Wds", Scope = "member", Target = "Tik4Net.Objects.Interfaces.InterfaceWireless.#WdsDefaultBridge")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Ssid", Scope = "member", Target = "Tik4Net.Objects.Interfaces.InterfaceWireless.#WdsIgnoreSsid")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Wds", Scope = "member", Target = "Tik4Net.Objects.Interfaces.InterfaceWireless.#WdsIgnoreSsid")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Wds", Scope = "member", Target = "Tik4Net.Objects.Interfaces.InterfaceWireless.#WdsMode")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "Tik4Net.Objects.Ip")]
