//*********************************************************
//  Autogenerated 9.4.2011 12:11:12
//*********************************************************
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/*
!re
=.id=*12
=name=eth4_OnBoard
=mtu=1500
=l2mtu=1600
=mac-address=00:21:85:13:32:35
=arp=enabled
=disable-running-check=true
=auto-negotiation=true
=full-duplex=true
=cable-settings=default
=speed=100Mbps
=running=true
=slave=false
=disabled=false
=comment=
*/
namespace Tik4Net.Objects.Interfaces
{
    /// <summary>
    /// Represents one row in /interface/ethernet on mikrotik router.
    /// </summary>
    [TikEntity("/interface/ethernet", TikEntityEditMode.Editable)]    
    public sealed partial class InterfaceEthernet: TikEntityBase
    {
        /// <summary>
        /// Row arp property.
        /// </summary>
        [TikProperty("arp", typeof(string), false, TikPropertyEditMode.Editable)]
        public string Arp 
        { 
            get { return Properties.GetAsStringOrNull("arp"); }
            set { Properties.SetAttribute("arp", value); }
        }

        /// <summary>
        /// Row auto-negotiation property.
        /// </summary>
        [TikProperty("auto-negotiation", typeof(bool?), false, TikPropertyEditMode.Editable)]
        public bool? AutoNegotiation 
        { 
            get { return Properties.GetAsBooleanOrNull("auto-negotiation"); }
            set { Properties.SetAttribute("auto-negotiation", value); }
        }        	

        /// <summary>
        /// Row cable-settings property.
        /// </summary>
        [TikProperty("cable-settings", typeof(string), false, TikPropertyEditMode.Editable)]
        public string CableSettings 
        { 
            get { return Properties.GetAsStringOrNull("cable-settings"); }
            set { Properties.SetAttribute("cable-settings", value); }
        }        	

        /// <summary>
        /// Row comment property.
        /// </summary>
        [TikProperty("comment", typeof(string), false, TikPropertyEditMode.Editable)]
        public string Comment 
        { 
            get { return Properties.GetAsStringOrNull("comment"); }
            set { Properties.SetAttribute("comment", value); }
        }        	

        /// <summary>
        /// Row disabled property.
        /// </summary>
        [TikProperty("disabled", typeof(bool), true, TikPropertyEditMode.Editable)]
        public bool Disabled 
        { 
            get { return Properties.GetAsBoolean("disabled"); }
            set { Properties.SetAttribute("disabled", value); }
        }        	

        /// <summary>
        /// Row disable-running-check property.
        /// </summary>
        [TikProperty("disable-running-check", typeof(bool?), false, TikPropertyEditMode.Editable)]
        public bool? DisableRunningCheck 
        { 
            get { return Properties.GetAsBooleanOrNull("disable-running-check"); }
            set { Properties.SetAttribute("disable-running-check", value); }
        }        	

        /// <summary>
        /// Row full-duplex property.
        /// </summary>
        [TikProperty("full-duplex", typeof(bool?), false, TikPropertyEditMode.ReadOnly)]
        public bool? FullDuplex 
        { 
            get { return Properties.GetAsBooleanOrNull("full-duplex"); }
            // Property R/O set { Properties.SetAttribute("full-duplex", value); }
        }        	

        /// <summary>
        /// Row l2mtu property.
        /// </summary>
        [TikProperty("l2mtu", typeof(long?), false, TikPropertyEditMode.Editable)]
        public long? L2mtu 
        { 
            get { return Properties.GetAsInt64OrNull("l2mtu"); }
            set { Properties.SetAttribute("l2mtu", value); }
        }        	

        /// <summary>
        /// Row mac-address property.
        /// </summary>
        [TikProperty("mac-address", typeof(string), false, TikPropertyEditMode.Editable)]
        public string MacAddress 
        { 
            get { return Properties.GetAsStringOrNull("mac-address"); }
            set { Properties.SetAttribute("mac-address", value); }
        }        	

        /// <summary>
        /// Row mtu property.
        /// </summary>
        [TikProperty("mtu", typeof(long?), false, TikPropertyEditMode.Editable)]
        public long? Mtu 
        { 
            get { return Properties.GetAsInt64OrNull("mtu"); }
            set { Properties.SetAttribute("mtu", value); }
        }        	

        /// <summary>
        /// Row name property.
        /// </summary>
        [TikProperty("name", typeof(string), true, TikPropertyEditMode.Editable)]
        public string Name 
        { 
            get { return Properties.GetAsString("name"); }
            set { Properties.SetAttribute("name", value); }
        }        	

        /// <summary>
        /// Row running property.
        /// </summary>
        [TikProperty("running", typeof(bool?), false, TikPropertyEditMode.ReadOnly)]
        public bool? Running 
        { 
            get { return Properties.GetAsBooleanOrNull("running"); }
            // Property R/O set { Properties.SetAttribute("running", value); }
        }        	

        /// <summary>
        /// Row slave property.
        /// </summary>
        [TikProperty("slave", typeof(bool?), false, TikPropertyEditMode.Editable)]
        public bool? Slave 
        { 
            get { return Properties.GetAsBooleanOrNull("slave"); }
            set { Properties.SetAttribute("slave", value); }
        }        	

        /// <summary>
        /// Row speed property.
        /// </summary>
        [TikProperty("speed", typeof(string), false, TikPropertyEditMode.ReadOnly)]
        public string Speed 
        { 
            get { return Properties.GetAsStringOrNull("speed"); }
            // Property R/O set { Properties.SetAttribute("speed", value); }
        }        	
    }
    
    /// <summary>
    /// Represents list of rows in /interface/ethernet on mikrotik router.
    /// </summary>    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix")]    
    public sealed partial class InterfaceEthernetList : TikUnorderedList<InterfaceEthernet>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InterfaceEthernetList"/> class.
        /// Default active session (<see cref="TikSession.ActiveSession"/> is used).
        /// </summary>
        public InterfaceEthernetList() 
            : base()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InterfaceEthernetList"/> class.
        /// </summary>
        /// <param name="session">The session used to access mikrotik.</param>
        public InterfaceEthernetList(TikSession session)
            : base(session)
        {
        }
    }           
}