//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tik4Net.ApiGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tik4Net.ApiGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///
        ///namespace Tik4Net%EntityDotedPath%
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Represents one row in %EntityPath% on mikrotik router.
        ///    /// &lt;/summary&gt;
        ///    public class %EntityName%: TikEntityBase
        ///    {
        ///        %EntityProperties%
        ///
        ///        /// &lt;summary&gt;
        ///        /// See &lt;see cref=&quot;TikEntityBase.OnLoadFromEntityRow&quot;/&gt; for details.
        ///        /// &lt;/summary&gt;
        ///        protected override void OnLoadFromEntityRow(ITikEntityRow enti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClassTemplate {
            get {
                return ResourceManager.GetString("ClassTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to             attributes.CreateAttribute(&quot;%PropertyDataName%&quot;, string.Equals(entityRow.GetValue(&quot;%PropertyDataName%&quot;), &quot;true&quot;, StringComparison.OrdinalIgnoreCase));.
        /// </summary>
        internal static string LoadCodeBoolTemplate {
            get {
                return ResourceManager.GetString("LoadCodeBoolTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to             attributes.CreateAttribute(&quot;%PropertyDataName%&quot;, long.Parse(entityRow.GetValue(&quot;%PropertyDataName%&quot;), System.Globalization.CultureInfo.CurrentCulture));.
        /// </summary>
        internal static string LoadCodeInt64Template {
            get {
                return ResourceManager.GetString("LoadCodeInt64Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to             attributes.CreateAttribute(&quot;%PropertyDataName%&quot;, entityRow.GetValue(&quot;%PropertyDataName%&quot;));.
        /// </summary>
        internal static string LoadCodeTemplate {
            get {
                return ResourceManager.GetString("LoadCodeTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to         /// &lt;summary&gt;
        ///        /// Row %PropertyDataName% property.
        ///        /// &lt;/summary&gt;
        ///        public %FieldType% %PropertyName% 
        ///        { 
        ///            get { return attributes.GetAsInt64(&quot;%PropertyDataName%&quot;); }
        ///            set { attributes.SetAttribute(&quot;%PropertyDataName%&quot;, value); }
        ///        }        	.
        /// </summary>
        internal static string PropertyTemplate {
            get {
                return ResourceManager.GetString("PropertyTemplate", resourceCulture);
            }
        }
    }
}
