//*********************************************************
//  Autogenerated 14.3.2011 0:16:20
//*********************************************************
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/*
!re
=.id=*A6
=chain=dstnat
=action=dst-nat
=to-addresses=10.43.94.1
=to-ports=53
=protocol=udp
=dst-address=10.43.96.50
=dst-port=53
=invalid=false
=dynamic=false
=disabled=false
=comment=Temporary forward 10.43.96.50 DNS to 10.43.94.1 (Danik)
*/
namespace Tik4Net.Objects.Ip.Firewall
{
    /// <summary>
    /// Represents one row in /ip/firewall/nat on mikrotik router.
    /// </summary>
    [TikEntity("/ip/firewall/nat", TikEntityEditMode.Editable)]    
    public sealed partial class FirewallNat: TikEntityBase
    {
        /// <summary>
        /// Row action property.
        /// </summary>
        [TikProperty("action", typeof(string), false, TikPropertyEditMode.Editable)]
        public string Action 
        { 
            get { return Properties.GetAsStringOrNull("action"); }
            set { Properties.SetAttribute("action", value); }
        }

        /// <summary>
        /// Row comment property.
        /// </summary>
        [TikProperty("comment", typeof(string), false, TikPropertyEditMode.Editable)]
        public string Comment 
        { 
            get { return Properties.GetAsStringOrNull("comment"); }
            set { Properties.SetAttribute("comment", value); }
        }        	

        /// <summary>
        /// Row disabled property.
        /// </summary>
        [TikProperty("disabled", typeof(bool), true, TikPropertyEditMode.Editable)]
        public bool Disabled 
        { 
            get { return Properties.GetAsBoolean("disabled"); }
            set { Properties.SetAttribute("disabled", value); }
        }        	

        /// <summary>
        /// Row dst-address property.
        /// </summary>
        [TikProperty("dst-address", typeof(string), false, TikPropertyEditMode.Editable)]
        public string DstAddress 
        { 
            get { return Properties.GetAsStringOrNull("dst-address"); }
            set { Properties.SetAttribute("dst-address", value); }
        }        	

        /// <summary>
        /// Row dst-address-list property.
        /// </summary>
        [TikProperty("dst-address-list", typeof(string), false, TikPropertyEditMode.Editable)]
        public string DstAddressList 
        { 
            get { return Properties.GetAsStringOrNull("dst-address-list"); }
            set { Properties.SetAttribute("dst-address-list", value); }
        }        	

        /// <summary>
        /// Row dst-address-type property.
        /// </summary>
        [TikProperty("dst-address-type", typeof(string), false, TikPropertyEditMode.Editable)]
        public string DstAddressType 
        { 
            get { return Properties.GetAsStringOrNull("dst-address-type"); }
            set { Properties.SetAttribute("dst-address-type", value); }
        }        	

        /// <summary>
        /// Row dst-port property.
        /// </summary>
        [TikProperty("dst-port", typeof(string), false, TikPropertyEditMode.Editable)]
        public string DstPort 
        { 
            get { return Properties.GetAsStringOrNull("dst-port"); }
            set { Properties.SetAttribute("dst-port", value); }
        }        	

        /// <summary>
        /// Row dynamic property.
        /// </summary>
        [TikProperty("dynamic", typeof(bool?), false, TikPropertyEditMode.Editable)]
        public bool? Dynamic 
        { 
            get { return Properties.GetAsBooleanOrNull("dynamic"); }
            set { Properties.SetAttribute("dynamic", value); }
        }        	

        /// <summary>
        /// Row chain property.
        /// </summary>
        [TikProperty("chain", typeof(string), false, TikPropertyEditMode.Editable)]
        public string Chain 
        { 
            get { return Properties.GetAsStringOrNull("chain"); }
            set { Properties.SetAttribute("chain", value); }
        }        	

        /// <summary>
        /// Row in-interface property.
        /// </summary>
        [TikProperty("in-interface", typeof(string), false, TikPropertyEditMode.Editable)]
        public string InInterface 
        { 
            get { return Properties.GetAsStringOrNull("in-interface"); }
            set { Properties.SetAttribute("in-interface", value); }
        }        	

        /// <summary>
        /// Row invalid property.
        /// </summary>
        [TikProperty("invalid", typeof(bool?), false, TikPropertyEditMode.ReadOnly)]
        public bool? Invalid 
        { 
            get { return Properties.GetAsBooleanOrNull("invalid"); }
            // Property R/O set { Properties.SetAttribute("invalid", value); }
        }        	

        /// <summary>
        /// Row out-interface property.
        /// </summary>
        [TikProperty("out-interface", typeof(string), false, TikPropertyEditMode.Editable)]
        public string OutInterface 
        { 
            get { return Properties.GetAsStringOrNull("out-interface"); }
            set { Properties.SetAttribute("out-interface", value); }
        }        	

        /// <summary>
        /// Row protocol property.
        /// </summary>
        [TikProperty("protocol", typeof(string), false, TikPropertyEditMode.Editable)]
        public string Protocol 
        { 
            get { return Properties.GetAsStringOrNull("protocol"); }
            set { Properties.SetAttribute("protocol", value); }
        }        	

        /// <summary>
        /// Row routing-mark property.
        /// </summary>
        [TikProperty("routing-mark", typeof(string), false, TikPropertyEditMode.Editable)]
        public string RoutingMark 
        { 
            get { return Properties.GetAsStringOrNull("routing-mark"); }
            set { Properties.SetAttribute("routing-mark", value); }
        }        	

        /// <summary>
        /// Row src-address property.
        /// </summary>
        [TikProperty("src-address", typeof(string), false, TikPropertyEditMode.Editable)]
        public string SrcAddress 
        { 
            get { return Properties.GetAsStringOrNull("src-address"); }
            set { Properties.SetAttribute("src-address", value); }
        }        	

        /// <summary>
        /// Row src-address-list property.
        /// </summary>
        [TikProperty("src-address-list", typeof(string), false, TikPropertyEditMode.Editable)]
        public string SrcAddressList 
        { 
            get { return Properties.GetAsStringOrNull("src-address-list"); }
            set { Properties.SetAttribute("src-address-list", value); }
        }        	

        /// <summary>
        /// Row src-address-type property.
        /// </summary>
        [TikProperty("src-address-type", typeof(string), false, TikPropertyEditMode.Editable)]
        public string SrcAddressType 
        { 
            get { return Properties.GetAsStringOrNull("src-address-type"); }
            set { Properties.SetAttribute("src-address-type", value); }
        }        	

        /// <summary>
        /// Row to-addresses property.
        /// </summary>
        [TikProperty("to-addresses", typeof(string), false, TikPropertyEditMode.Editable)]
        public string ToAddresses 
        { 
            get { return Properties.GetAsStringOrNull("to-addresses"); }
            set { Properties.SetAttribute("to-addresses", value); }
        }        	

        /// <summary>
        /// Row to-ports property.
        /// </summary>
        [TikProperty("to-ports", typeof(string), false, TikPropertyEditMode.Editable)]
        public string ToPorts 
        { 
            get { return Properties.GetAsStringOrNull("to-ports"); }
            set { Properties.SetAttribute("to-ports", value); }
        }        	
    }
    
    /// <summary>
    /// Represents list of rows in /ip/firewall/nat on mikrotik router.
    /// </summary>    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix")]    
    public sealed partial class FirewallNatList : TikList<FirewallNat>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FirewallNatList"/> class.
        /// Default active session (<see cref="TikSession.ActiveSession"/> is used).
        /// </summary>
        public FirewallNatList() 
            : base()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FirewallNatList"/> class.
        /// </summary>
        /// <param name="session">The session used to access mikrotik.</param>
        public FirewallNatList(TikSession session)
            : base(session)
        {
        }
    }           
}