//*********************************************************
//  Autogenerated 9.4.2011 12:11:11
//*********************************************************
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/*
!re
=.id=*8
=name=danik
=type=pptp-in
=dynamic=false
=running=false
=disabled=false
=comment=
*/
namespace Tik4Net.Objects
{
    /// <summary>
    /// Represents one row in /interface on mikrotik router.
    /// </summary>
    [TikEntity("/interface", TikEntityEditMode.Editable)]    
    public sealed partial class Interface: TikEntityBase
    {
        /// <summary>
        /// Row comment property.
        /// </summary>
        [TikProperty("comment", typeof(string), false, TikPropertyEditMode.Editable)]
        public string Comment 
        { 
            get { return Properties.GetAsStringOrNull("comment"); }
            set { Properties.SetAttribute("comment", value); }
        }

        /// <summary>
        /// Row disabled property.
        /// </summary>
        [TikProperty("disabled", typeof(bool), true, TikPropertyEditMode.Editable)]
        public bool Disabled 
        { 
            get { return Properties.GetAsBoolean("disabled"); }
            set { Properties.SetAttribute("disabled", value); }
        }        	

        /// <summary>
        /// Row dynamic property.
        /// </summary>
        [TikProperty("dynamic", typeof(bool?), false, TikPropertyEditMode.Editable)]
        public bool? Dynamic 
        { 
            get { return Properties.GetAsBooleanOrNull("dynamic"); }
            set { Properties.SetAttribute("dynamic", value); }
        }        	

        /// <summary>
        /// Row l2mtu property.
        /// </summary>
        [TikProperty("l2mtu", typeof(long?), false, TikPropertyEditMode.Editable)]
        public long? L2mtu 
        { 
            get { return Properties.GetAsInt64OrNull("l2mtu"); }
            set { Properties.SetAttribute("l2mtu", value); }
        }        	

        /// <summary>
        /// Row mtu property.
        /// </summary>
        [TikProperty("mtu", typeof(long?), false, TikPropertyEditMode.Editable)]
        public long? Mtu 
        { 
            get { return Properties.GetAsInt64OrNull("mtu"); }
            set { Properties.SetAttribute("mtu", value); }
        }        	

        /// <summary>
        /// Row name property.
        /// </summary>
        [TikProperty("name", typeof(string), true, TikPropertyEditMode.Editable)]
        public string Name 
        { 
            get { return Properties.GetAsString("name"); }
            set { Properties.SetAttribute("name", value); }
        }        	

        /// <summary>
        /// Row running property.
        /// </summary>
        [TikProperty("running", typeof(bool?), false, TikPropertyEditMode.ReadOnly)]
        public bool? Running 
        { 
            get { return Properties.GetAsBooleanOrNull("running"); }
            // Property R/O set { Properties.SetAttribute("running", value); }
        }        	

        /// <summary>
        /// Row type property.
        /// </summary>
        [TikProperty("type", typeof(string), false, TikPropertyEditMode.Editable)]
        public string Type 
        { 
            get { return Properties.GetAsStringOrNull("type"); }
            set { Properties.SetAttribute("type", value); }
        }        	
    }
    
    /// <summary>
    /// Represents list of rows in /interface on mikrotik router.
    /// </summary>    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix")]    
    public sealed partial class InterfaceList : TikUnorderedList<Interface>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InterfaceList"/> class.
        /// Default active session (<see cref="TikSession.ActiveSession"/> is used).
        /// </summary>
        public InterfaceList() 
            : base()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="InterfaceList"/> class.
        /// </summary>
        /// <param name="session">The session used to access mikrotik.</param>
        public InterfaceList(TikSession session)
            : base(session)
        {
        }
    }           
}